#!/usr/bin/env python
# -*- coding: utf-8 -*-

import gtk, pygtk
from optparse import OptionParser
from DrPrintGui.MainWin import MainWin
from DrPrintBackend import Backend

if __name__ == "__main__":

   ## Analyze comand line options
   usage = "usage: %prog [options] [file]"
   parser = OptionParser(usage=usage)
   parser.add_option("-u", "--user", dest="user",default=None,
                     help = "set username to use for the ssh connection",
                     metavar="user")
   
   (option, args) = parser.parse_args()

   if len(args) > 0:
      filename = args[0]
   else:
      filename = None

   # The backend doing network work.
   backend = Backend()
   
   # ...and the Gtk main window.
   mw = MainWin(backend = backend,
                user = option.user,
                filename = filename)

   ## Show all :)
   mw.show()

   ## ..and let's go!
   gtk.main()
