#!/usr/bin/env python

import gtk, pygtk
from DrPrintGui.MainWin import MainWin
from DrPrintBackend import Backend

if __name__ == "__main__":

   backend = Backend()
   
   mw = MainWin(backend)

   mw.show()

   gtk.main()
