Document: drprint
Title: Debian drprint Manual
Author: <insert document author here>
Abstract: This manual describes what drprint is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/drprint/drprint.sgml.gz

Format: postscript
Files: /usr/share/doc/drprint/drprint.ps.gz

Format: text
Files: /usr/share/doc/drprint/drprint.text.gz

Format: HTML
Index: /usr/share/doc/drprint/html/index.html
Files: /usr/share/doc/drprint/html/*.html
